sa:SimuAnnealParDoc.o \
StocConj.o \
StaticDoc.o \
cmpannealdoc.o \
dlgprogress.o \
reverse.o \
CMPFile.o \
CMPIndexFile.o \
SegyMultiGroup.o \
range.o \
main.o \
filedialog.o \
makesvsys.o \
calc.o \
dlgcalc.o \
dlgdrawpartcmp.o \
dlgmakesvsys.o \
dlgmotif.o \
drawpartcmp.o \
SvSysDoc5.o \
SvSysDoc.o \
SvSysDoc2.o \
SvSysDoc3.o \
SvSysDoc4.o \
FHString.o \
FHGlobal.o
	 CC -o sa \SimuAnnealParDoc.o \
StocConj.o \
StaticDoc.o \
cmpannealdoc.o \
dlgprogress.o \
reverse.o \
CMPFile.o \
CMPIndexFile.o \
SegyMultiGroup.o \
range.o \
main.o \
filedialog.o \
makesvsys.o \
calc.o \
dlgcalc.o \
dlgdrawpartcmp.o \
dlgmakesvsys.o \
dlgmotif.o \
drawpartcmp.o \
SvSysDoc5.o \
SvSysDoc.o \
SvSysDoc2.o \
SvSysDoc3.o \
SvSysDoc4.o \
FHString.o \
FHGlobal.o \
-lXm -lXt -lX11 
SimuAnnealParDoc.o: SimuAnnealParDoc.cpp 
	 CC -c SimuAnnealParDoc.cpp 
StocConj.o: StocConj.cpp 
	 CC -c StocConj.cpp 
StaticDoc.o: StaticDoc.cpp 
	 CC -c StaticDoc.cpp 
cmpannealdoc.o: cmpannealdoc.cpp 
	 CC -c cmpannealdoc.cpp 
dlgprogress.o: dlgprogress.cpp 
	 CC -c dlgprogress.cpp 
reverse.o: reverse.cpp 
	 CC -c reverse.cpp 
CMPFile.o: CMPFile.cpp 
	 CC -c CMPFile.cpp 
CMPIndexFile.o: CMPIndexFile.cpp 
	 CC -c CMPIndexFile.cpp 
SegyMultiGroup.o: SegyMultiGroup.cpp 
	 CC -c SegyMultiGroup.cpp 
range.o: range.cpp 
	 CC -c range.cpp 
main.o: main.cpp 
	 CC -c main.cpp 
filedialog.o: filedialog.cpp 
	 CC -c filedialog.cpp 
makesvsys.o: makesvsys.cpp 
	 CC -c makesvsys.cpp 
calc.o: calc.cpp 
	 CC -c calc.cpp 
dlgcalc.o: dlgcalc.cpp 
	 CC -c dlgcalc.cpp 
dlgdrawpartcmp.o: dlgdrawpartcmp.cpp 
	 CC -c dlgdrawpartcmp.cpp 
dlgmakesvsys.o: dlgmakesvsys.cpp 
	 CC -c dlgmakesvsys.cpp 
dlgmotif.o: dlgmotif.cpp 
	 CC -c dlgmotif.cpp 
drawpartcmp.o: drawpartcmp.cpp 
	 CC -c drawpartcmp.cpp 
SvSysDoc5.o: SvSysDoc5.cpp 
	 CC -c SvSysDoc5.cpp 
SvSysDoc.o: SvSysDoc.cpp 
	 CC -c SvSysDoc.cpp 
SvSysDoc2.o: SvSysDoc2.cpp 
	 CC -c SvSysDoc2.cpp 
SvSysDoc3.o: SvSysDoc3.cpp 
	 CC -c SvSysDoc3.cpp 
SvSysDoc4.o: SvSysDoc4.cpp 
	 CC -c SvSysDoc4.cpp 
FHString.o: FHString.cpp 
	 CC -c FHString.cpp 
FHGlobal.o: FHGlobal.cpp 
	 CC -c FHGlobal.cpp 
